---
- name: Configure webserver with Nginx and TLS
  hosts: all
  become: true
  gather_facts: false

  vars:
    tls_dir: /etc/nginx/ssl/
    key_file: nginx.key
    cert_file: nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
    #http_port: 8080
    #https_port: 8443

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:

    - name: Ensure nginx is installed
      # package - Устанавливает/удаляет пакеты с использованием менеджера пакетов хоста. ansible-doc package
      ansible.builtin.package:
        name: nginx
        update_cache: true
      notify: Restart nginx

    - name: Create directories for TLS sertificate
      file:
        path: "{{ tls_dir }}"
        state: directory
        mode: '0750'
      notify: Restart nginx

    - name: Copy TLS files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tls_dir }}"
        mode: '0644'
      loop:
        - "{{ key_file }}"
        - "{{ cert_file }}"
      notify: Restart nginx

    - name: Manage nginx config template
      ansible.builtin.template:
        src: playbooks/templates/nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: '0644'
      notify: Restart nginx

    - name: Enable configuration
      # file - Устанавливает атрибуты файла, символической ссылки или каталога. ansible-doc file
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Install home page
      # template - Создает файл на основе шаблона и копирует его на хосты. ansible-doc template
      ansible.builtin.template:
        src: playbooks/templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Restart nginx
      # service - Запускает, останавливает или перезапускает службу. ansible-doc service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
...
